# Manually Regenerate AppResources.Designer.cs
# Parses .resx file and generates the Designer.cs file
# This is a workaround when Visual Studio's automatic regeneration fails

Write-Host "????????????????????????????????????????????????????????????????" -ForegroundColor Cyan
Write-Host "?      Manual AppResources.Designer.cs Regeneration Tool       ?" -ForegroundColor Cyan
Write-Host "????????????????????????????????????????????????????????????????" -ForegroundColor Cyan
Write-Host ""

$resxFile = "Resources\Strings\AppResources.resx"
$designerFile = "Resources\Strings\AppResources.Designer.cs"

if (-not (Test-Path $resxFile)) {
    Write-Host "ERROR: $resxFile not found!" -ForegroundColor Red
    exit 1
}

Write-Host "Reading $resxFile..." -ForegroundColor Cyan

# Load and parse XML
[xml]$xml = Get-Content $resxFile -Encoding UTF8

# Extract all resource entries
$resources = $xml.root.data | Where-Object { $_.name -ne $null }

Write-Host "Found $($resources.Count) resource strings" -ForegroundColor Green
Write-Host ""

# Generate Designer.cs content
$designerContent = @"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbientSleeper.Resources.Strings {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AmbientSleeper.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
"@

# Add property for each resource
foreach ($resource in $resources) {
    $name = $resource.name
    $value = $resource.value
    
    # Escape and sanitize value for XML comment - remove newlines and special chars
    $valueEscaped = $value -replace '\r?\n', ' ' -replace '\s+', ' '
    $valueEscaped = $valueEscaped.Trim()
    if ($valueEscaped.Length -gt 100) {
        $valueEscaped = $valueEscaped.Substring(0, 100) + "..."
    }
    $valueEscaped = $valueEscaped -replace '&', '&amp;' -replace '<', '&lt;' -replace '>', '&gt;' -replace '"', '&quot;' -replace "'", '&apos;'
    
    $designerContent += @"
        /// <summary>
        /// Looks up a localized string similar to $valueEscaped
        /// </summary>
        public static string $name {
            get {
                return ResourceManager.GetString("$name", resourceCulture);
            }
        }
        
"@
}

# Close the class
$designerContent += @"
    }
}
"@

# Write the file
Write-Host "Writing $designerFile..." -ForegroundColor Cyan
$utf8WithoutBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText((Join-Path (Get-Location) $designerFile), $designerContent, $utf8WithoutBom)

Write-Host ""
Write-Host "? Designer.cs regenerated successfully!" -ForegroundColor Green
Write-Host "   $($resources.Count) properties generated" -ForegroundColor White
Write-Host ""
Write-Host "Next step: Rebuild the solution" -ForegroundColor Cyan
Write-Host ""
