//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pemdas.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pemdas.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve already completed today&apos;s puzzle! Come back tomorrow..
        /// </summary>
        internal static string AlreadyCompleted {
            get {
                return ResourceManager.GetString("AlreadyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PEMDAS - Daily Math Challenge.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Streak.
        /// </summary>
        internal static string BestStreak {
            get {
                return ResourceManager.GetString("BestStreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boss.
        /// </summary>
        internal static string Boss {
            get {
                return ResourceManager.GetString("Boss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build an equation to reach: {0}.
        /// </summary>
        internal static string BuildEquation {
            get {
                return ResourceManager.GetString("BuildEquation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build It.
        /// </summary>
        internal static string BuildIt {
            get {
                return ResourceManager.GetString("BuildIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string ButtonClear {
            get {
                return ResourceManager.GetString("ButtonClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint.
        /// </summary>
        internal static string ButtonHint {
            get {
                return ResourceManager.GetString("ButtonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Result.
        /// </summary>
        internal static string ButtonShare {
            get {
                return ResourceManager.GetString("ButtonShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string ButtonSubmit {
            get {
                return ResourceManager.GetString("ButtonSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct! You earned {0} points!.
        /// </summary>
        internal static string CorrectAnswer {
            get {
                return ResourceManager.GetString("CorrectAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creative.
        /// </summary>
        internal static string Creative {
            get {
                return ResourceManager.GetString("Creative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Streak.
        /// </summary>
        internal static string CurrentStreak {
            get {
                return ResourceManager.GetString("CurrentStreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        internal static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        internal static string Easy {
            get {
                return ResourceManager.GetString("Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your answer....
        /// </summary>
        internal static string EnterAnswer {
            get {
                return ResourceManager.GetString("EnterAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while checking your answer. Please try again..
        /// </summary>
        internal static string ErrorCheckingAnswer {
            get {
                return ResourceManager.GetString("ErrorCheckingAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during subscription. Please try again later..
        /// </summary>
        internal static string ErrorDuringSubscription {
            get {
                return ResourceManager.GetString("ErrorDuringSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting the hint..
        /// </summary>
        internal static string ErrorGettingHint {
            get {
                return ResourceManager.GetString("ErrorGettingHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading your profile. Please try again..
        /// </summary>
        internal static string ErrorLoadingProfile {
            get {
                return ResourceManager.GetString("ErrorLoadingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load today&apos;s puzzle. Please restart the app..
        /// </summary>
        internal static string ErrorLoadingPuzzle {
            get {
                return ResourceManager.GetString("ErrorLoadingPuzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the puzzle. Please try again..
        /// </summary>
        internal static string ErrorLoadingPuzzleTryAgain {
            get {
                return ResourceManager.GetString("ErrorLoadingPuzzleTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load user progress..
        /// </summary>
        internal static string FailedToLoadUserProgress {
            get {
                return ResourceManager.GetString("FailedToLoadUserProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Premium!.
        /// </summary>
        internal static string GoPremium {
            get {
                return ResourceManager.GetString("GoPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        internal static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hints.
        /// </summary>
        internal static string Hints {
            get {
                return ResourceManager.GetString("Hints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You earned a hint token!.
        /// </summary>
        internal static string HintTokenEarned {
            get {
                return ResourceManager.GetString("HintTokenEarned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint Tokens Available.
        /// </summary>
        internal static string HintTokensAvailable {
            get {
                return ResourceManager.GetString("HintTokensAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hint tokens available. Watch an ad to earn one?.
        /// </summary>
        internal static string NoHintTokens {
            get {
                return ResourceManager.GetString("NoHintTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puzzle loaded. Please restart the app..
        /// </summary>
        internal static string NoPuzzleLoaded {
            get {
                return ResourceManager.GetString("NoPuzzleLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puzzle to share..
        /// </summary>
        internal static string NoPuzzleToShare {
            get {
                return ResourceManager.GetString("NoPuzzleToShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an answer first..
        /// </summary>
        internal static string PleaseEnterAnswer {
            get {
                return ResourceManager.GetString("PleaseEnterAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access puzzle archives.
        /// </summary>
        internal static string PremiumFeature1 {
            get {
                return ResourceManager.GetString("PremiumFeature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited practice mode.
        /// </summary>
        internal static string PremiumFeature2 {
            get {
                return ResourceManager.GetString("PremiumFeature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced operators.
        /// </summary>
        internal static string PremiumFeature3 {
            get {
                return ResourceManager.GetString("PremiumFeature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ads.
        /// </summary>
        internal static string PremiumFeature4 {
            get {
                return ResourceManager.GetString("PremiumFeature4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium Member.
        /// </summary>
        internal static string PremiumMember {
            get {
                return ResourceManager.GetString("PremiumMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puzzles Solved.
        /// </summary>
        internal static string PuzzlesSolved {
            get {
                return ResourceManager.GetString("PuzzlesSolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share My PEMDAS Result.
        /// </summary>
        internal static string ShareTitle {
            get {
                return ResourceManager.GetString("ShareTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solve It.
        /// </summary>
        internal static string SolveIt {
            get {
                return ResourceManager.GetString("SolveIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streak.
        /// </summary>
        internal static string Streak {
            get {
                return ResourceManager.GetString("Streak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe Now - $2.99/month.
        /// </summary>
        internal static string SubscribeButton {
            get {
                return ResourceManager.GetString("SubscribeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to access the puzzle archive!.
        /// </summary>
        internal static string SubscribeRequired {
            get {
                return ResourceManager.GetString("SubscribeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for subscribing!.
        /// </summary>
        internal static string SubscribeSuccess {
            get {
                return ResourceManager.GetString("SubscribeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to complete subscription. Please try again later..
        /// </summary>
        internal static string SubscriptionFailed {
            get {
                return ResourceManager.GetString("SubscriptionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Challenge.
        /// </summary>
        internal static string TabDailyChallenge {
            get {
                return ResourceManager.GetString("TabDailyChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string TabProfile {
            get {
                return ResourceManager.GetString("TabProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time&apos;s up!.
        /// </summary>
        internal static string TimeUp {
            get {
                return ResourceManager.GetString("TimeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Points.
        /// </summary>
        internal static string TotalPoints {
            get {
                return ResourceManager.GetString("TotalPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tricky.
        /// </summary>
        internal static string Tricky {
            get {
                return ResourceManager.GetString("Tricky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to access archive at this time..
        /// </summary>
        internal static string UnableToAccessArchive {
            get {
                return ResourceManager.GetString("UnableToAccessArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to share at this time..
        /// </summary>
        internal static string UnableToShare {
            get {
                return ResourceManager.GetString("UnableToShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to show ad at this time..
        /// </summary>
        internal static string UnableToShowAd {
            get {
                return ResourceManager.GetString("UnableToShowAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Puzzle Archive.
        /// </summary>
        internal static string ViewArchive {
            get {
                return ResourceManager.GetString("ViewArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not quite right. Try again!.
        /// </summary>
        internal static string WrongAnswer {
            get {
                return ResourceManager.GetString("WrongAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Stats.
        /// </summary>
        internal static string YourStats {
            get {
                return ResourceManager.GetString("YourStats", resourceCulture);
            }
        }
    }
}
